### ISSUE TITLE
Remove # from the URL

### ISSUE THREAD

**Issue by masteradit** [masteradit/AllSQL#11]
When we go to https://sql.allmityapp.com, it adds a `/#/` to the URL.

**Comment by Kushagrasaxena-13** [comment]
hey I want to work on this issue but when fork your project to my android studio its showing a error in **### lib>widgets > generated_plugin_registrant**  in registerPlugins  that _**Undefined name 'SqflitePluginWeb'.**_

**Comment by masteradit** [comment]
Hey @Kushagrasaxena-13! I fixed this issue in this commit e58f5595555d3a7939f012231c94c1b3df2a87cd, which will be merged into master in the next release. You can check some other issues given [here](https://github.com/masteradit/AllSQL/issues). Maybe you can take up something else?

Regarding that error, run the project in release mode using `flutter run --release` command. I am not entirely sure why that error comes, it is related to the `sqflite_web` plugin. I have also created 2 issues https://github.com/deakjahn/sqflite_web/issues/18 and https://github.com/deakjahn/sqflite_web/issues/19 related to this.
