### ISSUE TITLE
[FEATURE REQUEST] Upgrade to latest Flutter version

### ISSUE THREAD

**Issue by masteradit** [masteradit/AllSQL#27]
Upgrade the AllSQL Flutter app to the latest version of Flutter, along with all the dependencies.

**Comment by rohithmada00** [comment]
Hello @masteradit , I can work on this

**Comment by masteradit** [comment]
> Hello @masteradit , I can work on this

Hi @rohithmada00, apologies for the late reply. I had already completed this a few days ago, it was a pretty big change as the dependencies we were using are no longer supported. So I decided to rewrite the entire application from scratch and also organise the code in a better way. I will be creating more issues soon, so feel free to star this repo and keep an eye on the issues tab.
